// Dati generati una tantum dai fascicoli Excel forniti dall'utente (13 file,
// un foglio per dispositivo): vedi conversazione. File temporaneo, da rimuovere
// insieme alla rotta subito dopo l'esecuzione.
import type { Device } from "@/lib/device-types";

export const NEW_CATEGORIES: string[] = ["Alzamalati", "Aste per flebo", "Compressori", "Deambulatori ascellari", "Elettromedicali vari", "Kinetek", "Letti", "Magnetoterapia", "Sollevatori", "Sponde"];

export const NEW_DEVICES: Device[] = [
  {
    codice: "N8AM",
    categoria: "Alzamalati",
    sottocategoria: null,
    marca: "TERMIGEA",
    modello: "014SO2",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-27",
    nota: null,
    foto: null,
  },
  {
    codice: "N9AM",
    categoria: "Alzamalati",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MI097",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-06",
    nota: null,
    foto: null,
  },
  {
    codice: "N19A",
    categoria: "Aste per flebo",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MI433+077PO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-03-18",
    nota: null,
    foto: null,
  },
  {
    codice: "N21A",
    categoria: "Aste per flebo",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MI433+077PO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-01",
    nota: null,
    foto: null,
  },
  {
    codice: "N14CM",
    categoria: "Compressori",
    sottocategoria: null,
    marca: "MEDILAND",
    modello: "017M+C",
    larghezza: null,
    stato: "noleggiato",
    cliente: "FANETTI+MATERASSO",
    telefono: null,
    contratto: null,
    dal: "2026-05-15",
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: numero contratto non registrato.",
    foto: null,
  },
  {
    codice: "N15CM",
    categoria: "Compressori",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058M+C",
    larghezza: null,
    stato: "noleggiato",
    cliente: "CANGIOLI",
    telefono: "3405046882",
    contratto: "8149",
    dal: "2026-08-25",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N53D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-02",
    nota: null,
    foto: null,
  },
  {
    codice: "N66D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756",
    larghezza: null,
    stato: "noleggiato",
    cliente: "BENCINI",
    telefono: "3383422706",
    contratto: "8117",
    dal: "2026-07-31",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N67D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756",
    larghezza: null,
    stato: "noleggiato",
    cliente: "TIZIANA PENNY",
    telefono: null,
    contratto: null,
    dal: "2026-07-17",
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: numero contratto non registrato.",
    foto: null,
  },
  {
    codice: "N68D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-04-30",
    nota: null,
    foto: null,
  },
  {
    codice: "N70D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756",
    larghezza: null,
    stato: "noleggiato",
    cliente: "MAGGAIOLI",
    telefono: "3471937529",
    contratto: "8112",
    dal: "2026-07-29",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N71D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "WIMED",
    modello: "035DEAMB",
    larghezza: null,
    stato: "noleggiato",
    cliente: "INNOCENTI",
    telefono: "3397482802",
    contratto: null,
    dal: "2026-06-22",
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: numero contratto non registrato.",
    foto: null,
  },
  {
    codice: "N72D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP756T",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-24",
    nota: null,
    foto: null,
  },
  {
    codice: "N73D",
    categoria: "Deambulatori ascellari",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058RP754A",
    larghezza: null,
    stato: "noleggiato",
    cliente: "BARONI",
    telefono: "3391183991",
    contratto: "8133",
    dal: "2026-08-08",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N2U",
    categoria: "Elettromedicali vari",
    sottocategoria: "Ultrasuono",
    marca: "IACER",
    modello: "066MIOSONIC",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-06-29",
    nota: null,
    foto: null,
  },
  {
    codice: "N6E",
    categoria: "Elettromedicali vari",
    sottocategoria: "Elettrostimolatore",
    marca: "IACER",
    modello: "066PHYSIO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-17",
    nota: null,
    foto: null,
  },
  {
    codice: "N2K",
    categoria: "Kinetek",
    sottocategoria: null,
    marca: "RO+TEN",
    modello: "",
    larghezza: null,
    stato: "noleggiato",
    cliente: "POGGIALI",
    telefono: "3490832188",
    contratto: "8140",
    dal: "2026-08-20",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N3K",
    categoria: "Kinetek",
    sottocategoria: null,
    marca: "RO+TEN",
    modello: "",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-06",
    nota: null,
    foto: null,
  },
  {
    codice: "N11L",
    categoria: "Letti",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058M180+058MP093",
    larghezza: null,
    stato: "guasto",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-06-22",
    nota: "Importato dall'archivio storico: annotazione \"GUASTO\" come ultima riga (dispositivo guasto).",
    foto: null,
  },
  {
    codice: "N12L",
    categoria: "Letti",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058M180+058MP093",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-25",
    nota: null,
    foto: null,
  },
  {
    codice: "N13L",
    categoria: "Letti",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MP093",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-26",
    nota: null,
    foto: null,
  },
  {
    codice: "N15L",
    categoria: "Letti",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MP093",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-24",
    nota: null,
    foto: null,
  },
  {
    codice: "N22M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066MAG2000",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-17",
    nota: null,
    foto: null,
  },
  {
    codice: "N23M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066MAG2000",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-01",
    nota: null,
    foto: null,
  },
  {
    codice: "M30M",
    categoria: "Magnetoterapia",
    sottocategoria: "Con materasso",
    marca: "NEWAGE",
    modello: "006MT",
    larghezza: null,
    stato: "guasto",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: annotazione \"GUASTA\" come ultima riga (dispositivo guasto).",
    foto: null,
  },
  {
    codice: "N32M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-30",
    nota: null,
    foto: null,
  },
  {
    codice: "N34M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-05",
    nota: null,
    foto: null,
  },
  {
    codice: "N36M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-07",
    nota: null,
    foto: null,
  },
  {
    codice: "N37M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "noleggiato",
    cliente: "FINESTAURI",
    telefono: "33879266719",
    contratto: "8058",
    dal: "2026-07-04",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N39M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-04",
    nota: null,
    foto: null,
  },
  {
    codice: "N41M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "noleggiato",
    cliente: "SOLDI",
    telefono: "3357480581",
    contratto: "8110",
    dal: "2026-07-28",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N42M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-17",
    nota: null,
    foto: null,
  },
  {
    codice: "N44M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-30",
    nota: null,
    foto: null,
  },
  {
    codice: "N45M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-05",
    nota: null,
    foto: null,
  },
  {
    codice: "N46M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "noleggiato",
    cliente: "TOGNACCINI",
    telefono: "3345457447",
    contratto: "8130",
    dal: "2026-08-07",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N47M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-24",
    nota: null,
    foto: null,
  },
  {
    codice: "N48M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-08",
    nota: null,
    foto: null,
  },
  {
    codice: "N50M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-03",
    nota: null,
    foto: null,
  },
  {
    codice: "N51M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-08",
    nota: null,
    foto: null,
  },
  {
    codice: "N52M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "IACER",
    modello: "066LAMAGNETO",
    larghezza: null,
    stato: "da_verificare",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-24",
    nota: "Da verificare: l'ultima riga dell'archivio storico riporta \"luca guiducci\", non chiaramente un noleggio cliente in corso.",
    foto: null,
  },
  {
    codice: "N53M",
    categoria: "Magnetoterapia",
    sottocategoria: null,
    marca: "COLPHARMA",
    modello: "203MAGNETO",
    larghezza: null,
    stato: "noleggiato",
    cliente: "LO COCO",
    telefono: "3703047255",
    contratto: "8125",
    dal: "2026-08-04",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N78RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP689",
    larghezza: null,
    stato: "da_pulire",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-29",
    nota: "Importato dall'archivio storico: risultava \"da pulire\" come ultima riga.",
    foto: null,
  },
  {
    codice: "N96RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP520",
    larghezza: null,
    stato: "noleggiato",
    cliente: "BARTOCINI",
    telefono: "3345952917",
    contratto: "7643",
    dal: "2026-01-31",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N98RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "WIMED",
    modello: "035RA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "PELLI",
    telefono: "3519172613",
    contratto: "7662",
    dal: "2026-02-13",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N121RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "SPES",
    modello: "009S301",
    larghezza: null,
    stato: "noleggiato",
    cliente: "GARCIA",
    telefono: "3661864853",
    contratto: null,
    dal: "2025-09-06",
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: numero contratto non registrato.",
    foto: null,
  },
  {
    codice: "N122RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP686",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-17",
    nota: null,
    foto: null,
  },
  {
    codice: "N123RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "WIMED",
    modello: "035RA",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-25",
    nota: null,
    foto: null,
  },
  {
    codice: "N127RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131SPARTA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "COTELLESSA",
    telefono: "3713428304",
    contratto: "7652",
    dal: "2026-02-04",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N129RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131SPARTA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "TONINELLI",
    telefono: "3355872953",
    contratto: "7787",
    dal: "2026-06-09",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N136RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP513",
    larghezza: null,
    stato: "da_verificare",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-09",
    nota: "Da verificare: l'ultima riga dell'archivio storico riporta \"NON FATTO CONTRATTO\", non chiaramente un noleggio cliente in corso.",
    foto: null,
  },
  {
    codice: "N137RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131MINI",
    larghezza: null,
    stato: "noleggiato",
    cliente: "GEREMIA",
    telefono: "3921220195",
    contratto: "8031",
    dal: "2026-06-27",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N138RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131SPARTA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "GOFFREDO",
    telefono: "3274334544",
    contratto: "7916",
    dal: "2026-05-13",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N139RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131SPARTA",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-06",
    nota: null,
    foto: null,
  },
  {
    codice: "N140RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131MINI",
    larghezza: null,
    stato: "noleggiato",
    cliente: "CRESCENZO",
    telefono: "3200259486",
    contratto: "7877",
    dal: "2026-04-28",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N142RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP520",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-18",
    nota: null,
    foto: null,
  },
  {
    codice: "N143RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "MORETTI",
    modello: "058RP520",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-03",
    nota: null,
    foto: null,
  },
  {
    codice: "N145RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131MINI",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-21",
    nota: null,
    foto: null,
  },
  {
    codice: "N146RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "SPES",
    modello: "009RA",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-22",
    nota: null,
    foto: null,
  },
  {
    codice: "N147RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "INTERMED",
    modello: "131SPARTA",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-24",
    nota: null,
    foto: null,
  },
  {
    codice: "N148RE",
    categoria: "Rollatori",
    sottocategoria: "Esterno",
    marca: "SPES",
    modello: "009RA",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N83R",
    categoria: "Rollatori",
    sottocategoria: "Interno",
    marca: "WIMED",
    modello: "035DA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "CALABRI",
    telefono: "3400969931",
    contratto: "8069",
    dal: "2026-07-10",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N87R",
    categoria: "Rollatori",
    sottocategoria: "Interno",
    marca: "WIMED",
    modello: "035DA",
    larghezza: null,
    stato: "noleggiato",
    cliente: "BRUNETTI",
    telefono: "3453463624",
    contratto: "8121",
    dal: "2026-08-01",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "NS1",
    categoria: "Sollevatori",
    sottocategoria: "Idraulico",
    marca: "MORETTI",
    modello: "058RP880",
    larghezza: null,
    stato: "noleggiato",
    cliente: "LANCIONI",
    telefono: "3282728021",
    contratto: "8010",
    dal: "2026-06-19",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "NS3",
    categoria: "Sollevatori",
    sottocategoria: "Idraulico",
    marca: "MORETTI",
    modello: "058RI701",
    larghezza: null,
    stato: "noleggiato",
    cliente: "PAGGETTI",
    telefono: "3397037870",
    contratto: "8055",
    dal: "2026-07-03",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "NS5",
    categoria: "Sollevatori",
    sottocategoria: "Elettrico",
    marca: "MORETTI",
    modello: "058RI701",
    larghezza: null,
    stato: "noleggiato",
    cliente: "GIUSTI",
    telefono: "3358189363",
    contratto: null,
    dal: "2026-07-16",
    alPrevisto: null,
    sanificazione: null,
    nota: "Importato dall'archivio storico: numero contratto non registrato.",
    foto: null,
  },
  {
    codice: "NS7",
    categoria: "Sollevatori",
    sottocategoria: "Elettrico",
    marca: "MORETTI",
    modello: "058RI828",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-23",
    nota: null,
    foto: null,
  },
  {
    codice: "N20SP",
    categoria: "Sponde",
    sottocategoria: null,
    marca: "MORETTI",
    modello: "058MP168",
    larghezza: null,
    stato: "noleggiato",
    cliente: "BASTIANELLI",
    telefono: "3294312802",
    contratto: "7430",
    dal: "2025-10-25",
    alPrevisto: null,
    sanificazione: null,
    nota: null,
    foto: null,
  },
  {
    codice: "N22SP",
    categoria: "Sponde",
    sottocategoria: null,
    marca: "TERMIGEA",
    modello: "014SP13",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-30",
    nota: null,
    foto: null,
  },
  {
    codice: "N23SP",
    categoria: "Sponde",
    sottocategoria: null,
    marca: "TERMIGEA",
    modello: "014SP13",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-08-06",
    nota: null,
    foto: null,
  },
  {
    codice: "N1CE",
    categoria: "Carrozzine",
    sottocategoria: "Elettrica",
    marca: "INTERMED",
    modello: "131ENJOY/42",
    larghezza: null,
    stato: "disponibile",
    cliente: null,
    telefono: null,
    contratto: null,
    dal: null,
    alPrevisto: null,
    sanificazione: "2026-07-06",
    nota: null,
    foto: null,
  },
];
